name: Build InstaCar APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Encontrar Gradle
        run: |
          echo "Procurando gradlew..."
          find . -name gradlew -type f

      - name: Dar permissão ao Gradle
        run: |
          GRADLEW=$(find . -name gradlew -type f | head -n 1)

          if [ -z "$GRADLEW" ]; then
            echo "ERRO: arquivo gradlew não encontrado!"
            exit 1
          fi

          echo "Gradle encontrado em: $GRADLEW"
          chmod +x "$GRADLEW"

      - name: Gerar APK
        run: |
          GRADLEW=$(find . -name gradlew -type f | head -n 1)

          if [ -z "$GRADLEW" ]; then
            echo "ERRO: arquivo gradlew não encontrado!"
            exit 1
          fi

          cd "$(dirname "$GRADLEW")"
          ./gradlew assembleDebug

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: InstaCar-APK
          path: '**/build
